### ISSUE TITLE
moodlemlbackend 3.0.2 not compatible with moodle

### ISSUE THREAD

**Issue by Simperfy** [moodlehq/moodle-mlbackend-python#47]
Moodle error:
"The selected predictions processor is not ready: The moodlemlbackend Python package is not compatible with this version of Moodle. The required version is "2.4.0" or higher as long as it is API-compatible. The installed version "3.0.2" is too high."

Is this normal or a bug?

`Moodle 3.11.1+ (Build: 20210723)`

**Comment by danmarsden** [comment]
yes - Moodle requires a specific version of the mlbackend which is "older" than the one we've pushed in here. To run it on our version at Catlyst we tend to hack the checks in Moodle or make the mlbackend report as being an older version - 3.0.2 will only "officially" work with Moodle 4.0 but it seems to work for fine in 3.9

**Comment by Simperfy** [comment]
Got it, thanks.
