### ISSUE TITLE
Issues installing mlbackend with debian11

### ISSUE THREAD

**Issue by Furiouss38** [moodlehq/moodle-mlbackend-python#48]
Hi,
I have some moodle servers in debian 10, with python Python 3.7.3, no problem with mlbackend 2.6.4
But our dev server where we test updates and our developper work on custom modules is in debian 11 because in the future our prod server will also be, with the default python packaged by debian : 

Python 3.9.2 :
`pip3 install moodlemlbackend==2.6.4
Collecting moodlemlbackend==2.6.4
  Using cached moodlemlbackend-2.6.4-py2.py3-none-any.whl (32 kB)
Collecting joblib<0.14,>=0.13.0
  Using cached joblib-0.13.2-py2.py3-none-any.whl (278 kB)
Collecting scikit-learn<0.22,>=0.21
  Using cached scikit-learn-0.21.3.tar.gz (12.2 MB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib<3.1,>=3.0
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement tensorflow<2.5,>=2.4.2 (from moodlemlbackend) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.8.0rc0, 2.8.0rc1, 2.8.0)
ERROR: No matching distribution found for tensorflow<2.5,>=2.4.2
`

With python 2.7.18 : 
`pip install moodlemlbackend==2.6.4
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting moodlemlbackend==2.6.4
  Using cached moodlemlbackend-2.6.4-py2.py3-none-any.whl (32 kB)
ERROR: Could not find a version that satisfies the requirement numpy<1.20,>=1.19.2 (from moodlemlbackend==2.6.4) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6)
ERROR: No matching distribution found for numpy<1.20,>=1.19.2 (from moodlemlbackend==2.6.4)
`

I tried to compile a python 3.7.9 to be closer to the version we have on debian 10 but i'm no python and compilation expert and there is an issue with it  :and I can't find why : 
`python3.7 -m pip install moodlemlbackend==2.6.4
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/moodlemlbackend/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/moodlemlbackend/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/moodlemlbackend/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/moodlemlbackend/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/moodlemlbackend/
Could not fetch URL https://pypi.org/simple/moodlemlbackend/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/moodlemlbackend/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement moodlemlbackend==2.6.4 (from versions: none)
ERROR: No matching distribution found for moodlemlbackend==2.6.4
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
`

So my question is, what can I do ?
I even tried to not specify the version of mlbackend but pip was unable to resolve conflicts : 

`ERROR: Cannot install moodlemlbackend==0.0.4, moodlemlbackend==0.0.5, moodlemlbackend==0.37.0, moodlemlbackend==1.0.0, moodlemlbackend==1.0.1, moodlemlbackend==2.0.0, moodlemlbackend==2.1.0, moodlemlbackend==2.2.1, moodlemlbackend==2.3.0, moodlemlbackend==2.3.1, moodlemlbackend==2.4.0, moodlemlbackend==2.5.0, moodlemlbackend==2.6.2, moodlemlbackend==2.6.4, moodlemlbackend==3.0.0 and moodlemlbackend==3.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    moodlemlbackend 3.0.2 depends on tensorflow<2.5 and >=2.4.2
    moodlemlbackend 3.0.0 depends on tensorflow<1.16 and >=1.15.5
    moodlemlbackend 2.6.4 depends on tensorflow<2.5 and >=2.4.2
    moodlemlbackend 2.6.2 depends on tensorflow<2.5 and >=2.4.2
    moodlemlbackend 2.5.0 depends on tensorflow<1.16 and >=1.15.5
    moodlemlbackend 2.4.0 depends on tensorflow<1.15 and >=1.14.0
    moodlemlbackend 2.3.1 depends on tensorflow<1.15 and >=1.14.0
    moodlemlbackend 2.3.0 depends on tensorflow<1.15 and >=1.14.0
    moodlemlbackend 2.2.1 depends on tensorflow<1.15 and >=1.14.0
    moodlemlbackend 2.1.0 depends on tensorflow<1.15 and >=1.14.0
    moodlemlbackend 2.0.0 depends on tensorflow<1.15 and >=1.14.0
    moodlemlbackend 1.0.1 depends on tensorflow<1.15 and >=1.14.0
    moodlemlbackend 1.0.0 depends on tensorflow<1.1 and >=1.0.0
    moodlemlbackend 0.37.0 depends on tensorflow<1.1 and >=1.0.0
    moodlemlbackend 0.0.5 depends on tensorflow<1.1 and >=1.0.0
    moodlemlbackend 0.0.4 depends on tensorflow<1.1 and >=1.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
`

If anyone has any idea, i'll we be appreciated :)

**Comment by douglasbagnall** [comment]
It won't work with Python 2.7.

I think the `tensorflow<2.5 and >=2.4.2` requirement is too tight, and could be loosened to allow just about any version > 1.14.

**Comment by Furiouss38** [comment]
Well at this point I was willing to try anything after trying to install it in all version possible.
Can I do something for the pip install to work with another tensorflow ? I'm not a python enthousiast  or expert, all I know to do is pip install :)

**Comment by douglasbagnall** [comment]
> Can I do something for the pip install to work with another tensorflow ?

I don't know (I don't use or control the pip package). Nevertheless I suspect the web is full of peoples attempts to get around this problem, if not with these particular packages.
